# SPDX-FileCopyrightText: 2025-2026 CodeMiner Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: scip-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs
variables:
  CONDA_NETWORK_TIMEOUT_SECS: 60
  CONDA_REPODATA_TIMEOUT_SECS: 30
