# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Unit tests for the declaration / generated-source classifiers in utils."""

from codenib.utils import file_has_generated_marker, is_declaration_file


def test_is_declaration_file_matches_type_stubs():
    assert is_declaration_file("src/dom.d.ts")
    assert is_declaration_file("src/jsx.d.ts:JSXInternal/IntrinsicElements")
    assert is_declaration_file("pkg/index.d.cts")
    assert is_declaration_file("pkg/index.d.mts")
    assert is_declaration_file("numpy/__init__.pyi")
    assert is_declaration_file("src/cython/mod.pxd")


def test_is_declaration_file_leaves_real_source_alone():
    assert not is_declaration_file("src/render.js")
    assert not is_declaration_file("src/diff/children.js:diffChildren()")
    assert not is_declaration_file("src/types.ts")  # a .ts file is real source
    assert not is_declaration_file("xarray/core/dataset.py")
    assert not is_declaration_file("")


def test_generated_marker_detects_common_banners(tmp_path):
    cases = {
        "xarray_style.py": (
            '"""Mixin classes with arithmetic operators."""\n\n'
            "# This file was generated using xarray.util.generate_ops. "
            "Do not edit manually.\n\nimport operator\n"
        ),
        "protobuf_style.py": (
            "# -*- coding: utf-8 -*-\n"
            "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
            "import sys\n"
        ),
        "go_style.go": (
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage main\n"
        ),
        "meta_style.js": ("/**\n * @generated\n */\nexport const x = 1;\n"),
    }
    for name, body in cases.items():
        path = tmp_path / name
        path.write_text(body)
        assert file_has_generated_marker(str(path)), name


def test_generated_marker_ignores_phrases_below_the_header(tmp_path):
    """Only the leading comment/docstring block counts.

    Both cases are real files in this repo that a whole-head byte scan flags:
    ``clients/codex_agent.py`` (a prompt string saying "DO NOT modify") and
    ``test/agent/test_bm25_search_e2e.py`` (an assertion message reading "No
    code chunks generated from the repository").
    """
    prompt_string = tmp_path / "agent.py"
    prompt_string.write_text(
        "# SPDX-License-Identifier: Apache-2.0\n\n"
        '"""A read-only agent client."""\n\n'
        "PROMPT = (\n"
        '    "- You are a READ-ONLY agent. DO NOT modify any files.\\n"\n'
        ")\n"
    )
    assert not file_has_generated_marker(str(prompt_string))

    assertion_message = tmp_path / "test_thing.py"
    assertion_message.write_text(
        '"""End-to-end search test."""\n\n'
        "def test_chunks(repo):\n"
        '    assert chunks, "No code chunks generated from the repository"\n'
    )
    assert not file_has_generated_marker(str(assertion_message))


def test_generated_marker_survives_missing_and_binary_files(tmp_path):
    assert not file_has_generated_marker(str(tmp_path / "nope.py"))
    binary = tmp_path / "blob.bin"
    binary.write_bytes(b"\x00\x01\x02\xff generated by nothing")
    assert not file_has_generated_marker(str(binary))
