# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

import re


def is_test_file(nid):
    """Check if a node ID belongs to a test file."""
    if ":" in nid:
        file_path = nid.split(":")[0]
    else:
        file_path = nid

    normalized = file_path.replace("\\", "/").lower()
    path_parts = [part for part in normalized.split("/") if part]
    if not path_parts:
        return False

    file_name = path_parts[-1]
    dir_parts = path_parts[:-1]

    # Directory-based heuristics.
    test_dirs = {"test", "tests", "__tests__", "spec", "specs"}
    if any(part in test_dirs for part in dir_parts):
        return True

    # Filename-based heuristics.
    if file_name.startswith("test"):
        return True
    if file_name.endswith(
        ("_test.py", "_test.js", "_test.ts", "_spec.py", "_spec.js", "_spec.ts")
    ):
        return True
    if ".test." in file_name or ".spec." in file_name:
        return True

    return False


_NON_SOURCE_DIR_PARTS = {"dist", "build", "out", "node_modules", "vendor"}
_NON_SOURCE_SUFFIXES = (
    ".min.js",
    ".d.ts",
    ".d.cts",
    ".d.mts",
    ".map",
    ".snap",
)


def is_non_source_file(nid):
    """Check whether a node ID / path is a build artifact or type-def stub.

    Bundles (``dist/``), minified output, sourcemaps, and TypeScript declaration
    stubs (``.d.ts`` / ``.d.cts``) are generated copies of the real source — they
    make poor localization ground truth, so synthesis should not anchor queries
    on them. Mirrors the assembly-time guard in
    ``rebuild_codenib_synthesis_dataset.py``.
    """
    if ":" in nid:
        file_path = nid.split(":")[0]
    else:
        file_path = nid

    normalized = file_path.replace("\\", "/").lower()
    path_parts = [part for part in normalized.split("/") if part]
    if not path_parts:
        return False

    if any(part in _NON_SOURCE_DIR_PARTS for part in path_parts[:-1]):
        return True
    return path_parts[-1].endswith(_NON_SOURCE_SUFFIXES)


_SOURCE_EXTENSIONS = frozenset(
    {
        ".py",
        ".pyx",
        ".go",
        ".rs",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".mjs",
        ".cjs",
        ".mts",
        ".cts",
        ".c",
        ".h",
        ".cc",
        ".cpp",
        ".hpp",
        ".cxx",
        ".java",
        ".rb",
        ".php",
        ".cs",
        ".kt",
        ".kts",
        ".swift",
        ".scala",
        ".lua",
        ".m",
        ".mm",
    }
)


def is_source_file(nid):
    """Check whether a node ID / path names a file in a language we parse.

    Distinct from :func:`is_non_source_file`, which asks "is this generated?".
    This asks "is this code at all?" — a manifest can legitimately point at a
    ``package.json`` or a README, and those do not belong on a code map.
    """
    if ":" in nid:
        file_path = nid.split(":")[0]
    else:
        file_path = nid

    normalized = file_path.replace("\\", "/").lower()
    name = normalized.rsplit("/", 1)[-1]
    if "." not in name:
        return False
    return f".{name.rsplit('.', 1)[-1]}" in _SOURCE_EXTENSIONS


_DECLARATION_SUFFIXES = (
    ".d.ts",
    ".d.cts",
    ".d.mts",
    ".pyi",
    ".pxd",
)


def is_declaration_file(nid):
    """Check whether a node ID / path is a type-declaration stub.

    Declaration files (``.d.ts`` / ``.pyi`` / ``.pxd``) describe types but hold
    no executable logic. They are legitimate source — unlike the build
    artifacts :func:`is_non_source_file` rejects — but a single one can declare
    hundreds of interfaces and thousands of fields, so on a symbol graph they
    outnumber hand-written code by an order of magnitude and hijack any
    degree- or PageRank-based "what matters here" ranking. Rankers should
    deprioritize them; retrieval may still surface them.
    """
    if ":" in nid:
        file_path = nid.split(":")[0]
    else:
        file_path = nid

    normalized = file_path.replace("\\", "/").lower()
    path_parts = [part for part in normalized.split("/") if part]
    if not path_parts:
        return False

    return path_parts[-1].endswith(_DECLARATION_SUFFIXES)


# Markers emitted in the header banner of machine-generated source, matched
# case-insensitively against the leading comment block only (see
# :func:`_header_comment_block`) — never the whole file.
#
# Most real banners name the generation: protobuf's "Generated by the protocol
# buffer compiler", gofmt's "Code generated by ... DO NOT EDIT.", xarray's
# "generated using xarray.util.generate_ops". Some only forbid editing —
# sympy's ``ask_generated.py`` opens with "Do NOT manually edit this file.
# Instead, run ./bin/ask_update.py." — so the bare form is included too. It is
# safe here precisely because the scan stops at the first line of real code:
# the phrases that used to false-positive were a prompt string ("DO NOT modify
# ... any files") and an assertion message, both of which are code.
_GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "generated using",
    "generated from",
    "generated automatically",
    "automatically generated",
    "autogenerated",
    "auto-generated",
    "code generated",
)
# The do-not-edit family, allowing an adverb: sympy's ``ask_generated.py`` opens
# "Do NOT manually edit this file." A plain substring misses that.
_DO_NOT_EDIT_RE = re.compile(r"do\s*n[o']?t\s+(?:\w+\s+){0,2}(?:edit|modify|change)")
_GENERATED_SCAN_BYTES = 2048
_HEADER_MAX_LINES = 60
# A generation banner is the first thing a generator writes, after at most a
# license stanza. Looking further turns long ``//!`` crate docs into matches:
# ruff's ``ruff_python_parser/src/lib.rs`` and astropy's ``formats.py`` both
# *discuss* generated code well inside their header prose.
_BANNER_MAX_LINES = 5
_COMMENT_PREFIXES = ("#", "//", "*", "--", ";", "%")
_DOCSTRING_DELIMITERS = ('"""', "'''")
_BLOCK_COMMENT_DELIMITERS = (("/*", "*/"), ("<!--", "-->"))


def _header_comment_block(text, max_lines=_HEADER_MAX_LINES):
    """Return the file's leading comment/docstring lines, lowercased.

    Stops at the first line of real code. Scanning the whole head of the file
    instead would misread ordinary source: CodeNib's own
    ``test/agent/test_bm25_search_e2e.py`` has an assertion message reading "No
    code chunks generated from the repository" 50 lines in.
    """
    header = []
    open_delimiter = None
    for line in text.splitlines()[:max_lines]:
        stripped = line.strip()
        if open_delimiter is not None:
            header.append(stripped)
            if open_delimiter in stripped:
                open_delimiter = None
            continue
        if not stripped:
            continue
        if stripped.startswith(_DOCSTRING_DELIMITERS):
            delimiter = stripped[:3]
            header.append(stripped)
            body = stripped[3:]
            if not body.endswith(delimiter) or not body:
                open_delimiter = delimiter
            continue
        block = next(
            (
                (opener, closer)
                for opener, closer in _BLOCK_COMMENT_DELIMITERS
                if stripped.startswith(opener)
            ),
            None,
        )
        if block is not None:
            opener, closer = block
            header.append(stripped)
            if closer not in stripped[len(opener) :]:
                open_delimiter = closer
            continue
        if stripped.startswith(_COMMENT_PREFIXES):
            header.append(stripped)
            continue
        break  # first real statement — the banner, if any, is already behind us
    return "\n".join(header).lower()


def source_has_generated_marker(source):
    """Check a source header already loaded from disk or a repository object."""
    if isinstance(source, bytes):
        source = source.decode("utf-8", errors="ignore")
    if not isinstance(source, str):
        return False
    header = _header_comment_block(source)
    banner = "\n".join(header.splitlines()[:_BANNER_MAX_LINES])
    if any(marker in banner for marker in _GENERATED_MARKERS):
        return True
    return bool(_DO_NOT_EDIT_RE.search(banner))


def file_has_generated_marker(path, max_bytes=_GENERATED_SCAN_BYTES):
    """Check whether the file at *path* declares itself machine-generated.

    Path-based rules cannot catch generated code that lives in an ordinary
    source file — e.g. ``xarray/core/_typed_ops.py``, which is emitted by
    ``xarray/util/generate_ops.py`` and defines hundreds of operator mixins.
    Such files dominate symbol-graph degree exactly the way declaration stubs
    do, so sniff the leading comment banner for a generation notice.

    Reads at most *max_bytes*; any I/O error means "unknown" (``False``).
    """
    try:
        with open(path, "rb") as handle:
            head = handle.read(max_bytes)
    except OSError:
        return False
    return source_has_generated_marker(head)


def wrap_code_snippet(code_snippet, start_line, end_line):
    """Wrap code snippet with line numbers"""
    lines = code_snippet.split("\n")

    # Remove trailing empty lines caused by trailing newlines
    while lines and lines[-1] == "":
        lines.pop()

    # Handle None values for files (use 0-based line numbering)
    if start_line is None:
        start_line = 0
    if end_line is None:
        end_line = len(lines) - 1

    max_line_number = start_line + len(lines) - 1
    number_width = len(str(max_line_number))
    return "\n".join(
        f"{str(i + start_line).rjust(number_width)} | {line}"
        for i, line in enumerate(lines)
    )
