# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Provider-neutral, per-file semantic fact contracts."""

from .adapters import fact_batch_from_scip_occurrences, fact_batches_from_code_graph
from .convergence import (
    ChangedFactFile,
    FactConvergenceError,
    FactConvergenceReport,
    FactOverlay,
    FactOverlayChange,
    compare_fact_snapshots,
)
from .model import (
    CAPABILITY_DEFINITIONS,
    CAPABILITY_DIAGNOSTICS,
    CAPABILITY_EDGES,
    CAPABILITY_OCCURRENCES,
    COMPLETENESS_COMPLETE,
    COMPLETENESS_FAILED,
    COMPLETENESS_PARTIAL,
    COMPLETENESS_SYNTACTIC,
    FACT_BATCH_SCHEMA_VERSION,
    PROVENANCE_CLANGD,
    PROVENANCE_FRAMEWORK,
    PROVENANCE_HEURISTIC,
    PROVENANCE_LSP,
    PROVENANCE_SCIP,
    PROVENANCE_SYNTACTIC,
    DiagnosticFact,
    EdgeFact,
    FactBatch,
    OccurrenceFact,
    SourceRange,
    SymbolFact,
    merge_fact_batches,
    sha256_digest,
)
from .resolver import (
    DefinitionHotCache,
    DefinitionIndex,
    ExactMonikerResolver,
    FactResolverPipeline,
    FrameworkRule,
    FrameworkRuleResolver,
    ResolutionPassReport,
    ResolutionResult,
    ResolverRegistry,
    SnapshotDefinitionResolver,
)

__all__ = [
    "CAPABILITY_DEFINITIONS",
    "CAPABILITY_DIAGNOSTICS",
    "CAPABILITY_EDGES",
    "CAPABILITY_OCCURRENCES",
    "ChangedFactFile",
    "COMPLETENESS_COMPLETE",
    "COMPLETENESS_FAILED",
    "COMPLETENESS_PARTIAL",
    "COMPLETENESS_SYNTACTIC",
    "DiagnosticFact",
    "DefinitionHotCache",
    "DefinitionIndex",
    "EdgeFact",
    "ExactMonikerResolver",
    "FACT_BATCH_SCHEMA_VERSION",
    "FactBatch",
    "FactConvergenceError",
    "FactConvergenceReport",
    "FactOverlay",
    "FactOverlayChange",
    "FactResolverPipeline",
    "FrameworkRule",
    "FrameworkRuleResolver",
    "OccurrenceFact",
    "PROVENANCE_CLANGD",
    "PROVENANCE_FRAMEWORK",
    "PROVENANCE_HEURISTIC",
    "PROVENANCE_LSP",
    "PROVENANCE_SCIP",
    "PROVENANCE_SYNTACTIC",
    "SourceRange",
    "SymbolFact",
    "fact_batch_from_scip_occurrences",
    "fact_batches_from_code_graph",
    "compare_fact_snapshots",
    "merge_fact_batches",
    "ResolutionPassReport",
    "ResolutionResult",
    "ResolverRegistry",
    "SnapshotDefinitionResolver",
    "sha256_digest",
]
