# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Build a dependency "codemap" subgraph for the web demo.

Walks the per-repo symbol graph's REFERENCE (call/use) edges out from a seed
symbol and returns a compact ``{nodes, edges}`` payload plus a Mermaid
``graph LR`` rendering the frontend can drop into the existing ``<Mermaid>``
component. Labels use the graph's ``unified_name`` (``file:Symbol()``) so the
map reads as code, not content-hash identities.

This is deliberately self-contained (no dependency on the ``DependencyAnalyzer``
plugin, which postdates this branch) — it walks the graph through the
``RepoDependencySearcher`` traversal helper that ships on the branch.
"""

from __future__ import annotations

import os
import re
from collections import deque
from functools import lru_cache
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Dict,
    List,
    Optional,
    Sequence,
    Set,
    Tuple,
)

from ..graph.code_graph import CodeGraph
from ..graph.hierarchy import (
    HierarchicalCodeGraph,
    attach_edge_routes,
    empty_hierarchy,
    hierarchy_for_view,
    hierarchy_from_view_nodes,
)
from ..graph.traverse_graph import RepoDependencySearcher
from ..repository_filters import repository_path_is_visible
from ..types import NODE_TYPE_FILE
from ..utils import (
    file_has_generated_marker,
    is_declaration_file,
    is_non_source_file,
    is_test_file,
    source_has_generated_marker,
)
from .entrypoints import discover_entry_points
from .repository_files import (
    git_blob_head,
    git_grep_paths,
    git_tree_paths,
    safe_repo_relative_path,
    valid_commit,
)

if TYPE_CHECKING:
    from ..repository_source_selection import RepositorySourceSelection
    from ..source_fingerprint import RepositorySourceReader

# Node types eligible as a focus / default seed (skip file/dir/import nodes).
_SYMBOL_TYPES = frozenset({"function", "method", "class"})
_GIT_PATHS_UNSET = object()
# Recognized source-file extensions (fallback when the repo root isn't known).
_SOURCE_EXTS = frozenset(
    {
        ".py",
        ".pyx",
        ".pyi",
        ".go",
        ".rs",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".mjs",
        ".cjs",
        ".c",
        ".h",
        ".cc",
        ".cpp",
        ".hpp",
        ".cxx",
        ".java",
        ".rb",
        ".php",
        ".cs",
        ".kt",
        ".kts",
        ".swift",
        ".scala",
        ".m",
        ".mm",
    }
)
_MERMAID_MAX_LABEL = 42
_DIR_TO_MODE = {"both": "all", "callees": "forward", "callers": "backward"}
EDGE_ANCHOR_SAMPLE = 12
_GENERATED_GREP_PATTERN = (
    r"@generated|generated (by|using|from|automatically)|automatically generated|"
    r"autogenerated|auto-generated|code generated|do[[:space:]]*n[o']?t"
    r"([[:space:]]+[[:alnum:]_-]+){0,2}[[:space:]]+(edit|modify|change)"
)


class _EdgeAnchorCollector:
    """Count distinct graph edges while retaining a bounded anchor sample.

    ``CodeGraph`` deduplicates reference edges by source, target, type, anchor
    file, and anchor line.  Callers must therefore feed each relation's graph
    edges from exactly one neighbour scan; this collector need not copy every
    anchor identity into a second unbounded set merely to deduplicate repeated
    bidirectional scans.
    """

    def __init__(self, sample_limit: int = EDGE_ANCHOR_SAMPLE) -> None:
        self._sample_limit = max(0, sample_limit)
        self._counts: Dict[Tuple[str, str], int] = {}
        self._samples: Dict[Tuple[str, str], List[Tuple[str, Optional[int]]]] = {}

    @staticmethod
    def _sort_key(identity: Tuple[str, Optional[int]]) -> Tuple[str, bool, int]:
        file_path, line = identity
        return (file_path, line is None, line if line is not None else 0)

    def add(self, key: Tuple[str, str], meta: Any) -> None:
        anchor_file = meta.get("anchor_file") if isinstance(meta, dict) else None
        if not anchor_file:
            return
        anchor_line = meta.get("anchor_line") if isinstance(meta, dict) else None
        line = anchor_line + 1 if isinstance(anchor_line, int) else None
        identity = (str(anchor_file), line)
        self._counts[key] = self._counts.get(key, 0) + 1
        if not self._sample_limit:
            return

        samples = self._samples.setdefault(key, [])
        if len(samples) < self._sample_limit:
            samples.append(identity)
            return

        largest_index = max(
            range(len(samples)), key=lambda index: self._sort_key(samples[index])
        )
        if self._sort_key(identity) < self._sort_key(samples[largest_index]):
            samples[largest_index] = identity

    def count(self, key: Tuple[str, str]) -> int:
        return self._counts.get(key, 0)

    def fields(self, key: Tuple[str, str]) -> Dict[str, Any]:
        count = self.count(key)
        if not count:
            return {}
        identities = sorted(
            self._samples.get(key, ()),
            key=self._sort_key,
        )
        samples = [{"file": file_path, "line": line} for file_path, line in identities]
        fields: Dict[str, Any] = {
            "anchors": samples,
            "weight": count,
        }
        hidden = count - len(samples)
        if hidden:
            fields["hidden_anchors"] = hidden
        return fields


def _normalize_path(path: str) -> str:
    """Repo-relative, forward-slashed — the form entry points are keyed by."""
    return path.replace("\\", "/").lstrip("./")


def _attrs(graph: CodeGraph, name: str) -> Dict[str, Any]:
    try:
        return graph.get_node_info_by_name(name) or {}
    except Exception:  # noqa: BLE001 - a missing/odd node must not 500 the map
        return {}


def _label(attrs: Dict[str, Any], identity: str) -> str:
    return (attrs.get("unified_name") or "").strip() or identity


def _short(label: str) -> str:
    """``pkg/dir/file.py:Class.method()`` -> ``file.py:Class.method()`` (capped)."""
    if ":" in label:
        path, _, sym = label.partition(":")
        base = path.rsplit("/", 1)[-1]
        short = f"{base}:{sym}" if sym else base
    else:
        short = label.rsplit("/", 1)[-1]
    if len(short) > _MERMAID_MAX_LABEL:
        short = short[: _MERMAID_MAX_LABEL - 1] + "…"
    return short


def _resolve(graph: CodeGraph, symbol: str) -> Optional[str]:
    """Map a user-entered symbol to a graph identity name.

    Tries an exact identity match first, then a case-insensitive match on the
    readable ``unified_name`` (exact, then shortest substring match, preferring
    function/method/class nodes).
    """
    if symbol in graph.name_to_vertex:
        return symbol
    needle = symbol.strip().lower()
    if not needle:
        return None
    best: Optional[str] = None
    best_score = float("inf")
    for v in graph.get_graph().vs:
        a = v.attributes()
        uni = a.get("unified_name") or ""
        if not uni:
            continue
        low = uni.lower()
        if low == needle:
            return a["name"]
        if needle in low:
            score = len(uni) - (1000 if a.get("type") in _SYMBOL_TYPES else 0)
            if score < best_score:
                best_score, best = score, a["name"]
    return best


class _DerivedFiles:
    """Memoized "is this file derived rather than hand-written?" oracle.

    Derived means a type-declaration stub (``.d.ts`` / ``.pyi``), a build
    artifact (``dist/``, ``*.min.js``), or a source file whose header declares
    it machine-generated. Such files are real graph content, but a single one
    can contribute thousands of symbols — Preact's ``src/dom.d.ts`` declares 127
    interfaces and ~1400 properties against ~5k lines of hand-written JS, and
    xarray's generated ``_typed_ops.py`` behaves the same way. Left unweighted
    they win every degree- and PageRank-based ranking, so the repo's default
    codemap ends up showing nothing but HTML attribute typedefs.

    The generated-header sniff needs to read files, so results are cached per
    instance; one instance lives for one codemap request.
    """

    def __init__(
        self,
        repo_dir: Optional[str] = None,
        repo_commit: Optional[str] = None,
        *,
        source_reader: Optional[RepositorySourceReader] = None,
    ) -> None:
        self._source_reader = source_reader
        self._repo_dir = (
            None
            if source_reader is not None
            else (os.path.realpath(repo_dir) if repo_dir else None)
        )
        self._repo_commit = (
            None
            if source_reader is not None
            else (repo_commit if valid_commit(repo_commit) else None)
        )
        self._cache: Dict[str, bool] = {}
        # Keep this potentially large set request-local. Concurrent requests
        # may evict the process-level entry, but this map never repeats the
        # repository-wide grep while classifying its files.
        self._git_generated_paths = (
            _git_generated_candidates(self._repo_dir, self._repo_commit)
            if self._repo_dir and self._repo_commit
            else None
        )

    def __call__(self, file_path: Any) -> bool:
        if not isinstance(file_path, str) or not file_path:
            return False
        cached = self._cache.get(file_path)
        if cached is None:
            cached = self._classify(file_path)
            self._cache[file_path] = cached
        return cached

    def _classify(self, file_path: str) -> bool:
        if is_declaration_file(file_path) or is_non_source_file(file_path):
            return True
        if self._source_reader is not None:
            relative = self._source_reader.captured_relative_path(file_path)
            if relative is None:
                return False
            head = self._source_reader.read_prefix(relative, max_bytes=2048)
            return source_has_generated_marker(head)
        if not self._repo_dir:
            return False
        relative = safe_repo_relative_path(self._repo_dir, file_path)
        if relative is None:
            return False
        if self._repo_commit:
            if (
                self._git_generated_paths is None
                or relative not in self._git_generated_paths
            ):
                return False
            head = git_blob_head(self._repo_dir, self._repo_commit, relative, 2048)
            return bool(head and source_has_generated_marker(head))
        candidate = os.path.realpath(os.path.join(self._repo_dir, relative))
        try:
            stat = os.stat(candidate)
        except OSError:
            return False
        return _live_file_has_generated_marker(
            candidate, stat.st_mtime_ns, stat.st_size
        )


@lru_cache(maxsize=16384)
def _live_file_has_generated_marker(path: str, mtime_ns: int, size: int) -> bool:
    """Cache header classification until the file's observable state changes."""
    del mtime_ns, size
    return file_has_generated_marker(path)


def _git_generated_candidates(repo_dir: str, commit: str) -> frozenset[str]:
    """Files mentioning a generation marker anywhere, found in one Git scan."""
    return git_grep_paths(repo_dir, commit, _GENERATED_GREP_PATTERN)


_NO_ENTRY = 1 << 20
# Directories holding code that exists to measure the repo, not to be the repo.
# `is_test_file` deliberately does not cover these — widening it there would
# change what the dataset-synthesis path accepts as ground truth — so the
# demotion lives here, where it only affects which symbol a reader lands on.
_SIDECAR_DIRS = frozenset(
    {
        "benchmark",
        "benchmarks",
        "bench",
        "example",
        "examples",
        "demo",
        "demos",
        "fixtures",
        "testdata",
    }
)


def _is_sidecar(path: str) -> bool:
    """True for benchmark/example/fixture code: real, but never the headline.

    sympy declares no entry point, so it falls through to out-degree and lands
    on ``sympy/polys/benchmarks/bench_solvers.py:eqs_165x165()`` — a generated
    165-equation benchmark, and the busiest symbol in the repo by a distance.
    """
    parts = _normalize_path(path).lower().split("/")
    return any(part in _SIDECAR_DIRS for part in parts[:-1])


def _entry_affinity(graph: CodeGraph, entry_paths: Sequence[str]) -> Dict[str, int]:
    """How close each symbol is to a declared entry point — lower is closer.

    A declared entry is usually a barrel, so "symbols defined in it" is often
    empty: preact's ``src/index.js`` and bat's ``src/lib.rs`` define nothing at
    all, and xarray's ``__init__.py`` defines two symbols that reference
    nothing. What they do have is the *file node's* outgoing references — the
    things they re-export. Following that one hop is what recovers
    ``DataArray``/``Dataset`` for xarray and ``PrettyPrinter`` for bat.

    Score is ``rank * 2`` for a symbol defined in the entry file and
    ``rank * 2 + 1`` for one it re-exports, so a direct hit in the primary entry
    beats a re-export from it, and both beat anything in the second entry.
    *entry_paths* must be manifest order (most authoritative first).
    """
    affinity: Dict[str, int] = {}

    def offer(name: str, score: int) -> None:
        if score < affinity.get(name, _NO_ENTRY):
            affinity[name] = score

    g = graph.get_graph()
    ranks = {path: rank for rank, path in enumerate(entry_paths)}
    if not ranks:
        return affinity
    for vertex in g.vs:
        attrs = vertex.attributes()
        node_type = attrs.get("type")
        if node_type == NODE_TYPE_FILE:
            rank = ranks.get(_normalize_path(attrs.get("name") or ""))
            if rank is None:
                continue
            for eid in g.incident(vertex.index, mode="out"):
                edge = g.es[eid]
                if edge.attributes().get("type") == "reference":
                    offer(g.vs[edge.target]["name"], rank * 2 + 1)
        elif node_type in _SYMBOL_TYPES:
            rank = ranks.get(_normalize_path(attrs.get("file") or ""))
            if rank is not None:
                offer(attrs["name"], rank * 2)
    return affinity


def _is_private(unified_name: str) -> bool:
    """``pkg/mod.py:Class._helper()`` -> True.

    Any underscore-prefixed component counts, not just the leaf: matplotlib's
    busiest entry-file symbol is ``_get_executable_info().impl``, whose leaf
    reads public but whose enclosing function is not. Only the symbol half is
    examined, so a ``__init__.py`` path never makes a symbol look private.
    """
    symbol = unified_name.rpartition(":")[2] or unified_name
    return any(part.startswith("_") for part in re.split(r"[./]", symbol) if part)


def _default_seed(
    graph: CodeGraph,
    derived: Optional[_DerivedFiles] = None,
    entry_paths: Optional[Sequence[str]] = None,
    source_allowed: Optional[Callable[[Dict[str, Any]], bool]] = None,
) -> Optional[str]:
    """The symbol a reader should land on, best-first.

    Three tiers, each a tiebreak on the one before:

    1. **Declared entry point.** If the repo's build manifest names files, a
       symbol in (or re-exported by) the most authoritative one wins. "What does
       this package expose" is the question a reader opens with, and
       ``package.json`` / ``pyproject.toml`` / ``Cargo.toml`` answer it exactly.
       Degree cannot know that. See :func:`_entry_affinity`.
    2. **Hand-written over derived.** Declaration stubs, generated files, build
       artifacts, tests and benchmark/example sidecars rank below real source
       but are not dropped, so an
       all-declaration repo still gets a map rather than nothing. Raw
       out-degree alone picks a 380-property ``SVGAttributes`` interface over
       the renderer.
    3. **Public over private.** Within a tier, a leading-underscore name loses
       to a public one — matplotlib's entry file offered
       ``_parse_to_version_info()`` when the package's API is what a reader
       wants.
    4. **Reference out-degree**, the original heuristic, to break the rest.
    """
    derived = derived or _DerivedFiles()
    g = graph.get_graph()
    affinity = _entry_affinity(graph, entry_paths or ())
    out_ref: Dict[int, int] = {}
    for e in g.es:
        if e.attributes().get("type") == "reference":
            out_ref[e.source] = out_ref.get(e.source, 0) + 1
    # Entry affinity dominates every later criterion. Restricting classification
    # to that winning tier avoids opening every source file on each request; in
    # the common case the first public, high-degree candidate is hand-written.
    candidates: List[Tuple[int, int, int, str, str]] = []
    for vertex in g.vs:
        a = vertex.attributes()
        if not a.get("unified_name") or a.get("type") not in _SYMBOL_TYPES:
            continue
        if source_allowed is not None and not source_allowed(a):
            continue
        name = a["name"]
        path = a.get("file") or name
        private = 1 if _is_private(a.get("unified_name") or name) else 0
        candidates.append(
            (
                affinity.get(name, _NO_ENTRY),
                private,
                out_ref.get(vertex.index, 0),
                name,
                path,
            )
        )
    if not candidates:
        return None

    winning_affinity = min(candidate[0] for candidate in candidates)
    tier = [candidate for candidate in candidates if candidate[0] == winning_affinity]
    # ``name`` breaks ties last so the seed is stable across graph build order.
    tier.sort(key=lambda item: (-item[1], item[2], item[3]), reverse=True)
    best_penalized: Optional[str] = None
    for _affinity, _private, _count, name, path in tier:
        penalized = is_test_file(path) or _is_sidecar(path) or derived(path)
        if not penalized:
            return name
        if best_penalized is None:
            best_penalized = name
    return best_penalized


def _is_external(
    a: Dict[str, Any],
    repo_dir: Optional[str] = None,
    repo_commit: Optional[str] = None,
    repo_paths: object = _GIT_PATHS_UNSET,
    source_reader: Optional[RepositorySourceReader] = None,
) -> bool:
    """True if a node has no openable in-repo source.

    External library symbols carry a dotted module path (e.g.
    ``setuptools.extension``) and no line; file/dir nodes carry no line either.
    When the repo root is known, "openable" means the file actually exists under
    it — mirroring the ``/source`` endpoint — so repo-root files like
    ``setup.py`` / ``main.go`` are NOT misflagged. Without a root, fall back to:
    needs a line, and the file is a path or has a known source extension.
    """
    f = a.get("file")
    s = a.get("start_line")
    if not isinstance(s, int) or not isinstance(f, str) or not f:
        return True
    if source_reader is not None:
        return source_reader.captured_relative_path(f) is None
    if repo_dir:
        root = os.path.realpath(repo_dir)
        relative = safe_repo_relative_path(root, f)
        if relative is None:
            return True
        if repo_commit:
            paths = (
                git_tree_paths(root, repo_commit)
                if repo_paths is _GIT_PATHS_UNSET
                else repo_paths
            )
            if paths is not None:
                return relative not in paths
            # Do not silently consult a different checkout when the requested
            # commit object is unavailable. Fall through to the shape heuristic.
        else:
            return not os.path.isfile(os.path.join(root, relative))
    return ("/" not in f) and (os.path.splitext(f)[1].lower() not in _SOURCE_EXTS)


def _pagerank(
    subref: Any, sub_names: List[str], derived_names: Set[str]
) -> List[float]:
    """PageRank over *subref*, restarting only on hand-written symbols.

    Falls back to uniform PageRank when every node is derived (no restart mass
    to distribute) or when the igraph build predates ``personalized_pagerank``.
    """
    reset = [0.0 if n in derived_names else 1.0 for n in sub_names]
    if any(reset) and not all(reset):
        try:
            return subref.personalized_pagerank(
                directed=True, damping=0.85, reset=reset
            )
        except (AttributeError, TypeError):  # older/newer igraph API
            pass
    return subref.pagerank(directed=True, damping=0.85)


def _score(
    graph: CodeGraph, names: List[str], derived_names: Optional[Set[str]] = None
) -> Tuple[Dict[str, float], Dict[str, int], Dict[str, int], Dict[str, float]]:
    """PageRank importance + community + reference count + entry score per node.

    All computed on the induced REFERENCE subgraph of *names* (cheap, <=120
    nodes). PageRank (rank-percentile in [0,1]) surfaces "core" symbols
    (referenced by other important code); community is Leiden/modularity on the
    undirected projection (igraph 0.11.9 has no directed Leiden), guarded so
    tiny/loose graphs collapse to one cluster; ``ref_count`` = in-degree (how
    many symbols reference this one); ``entry_score`` = out/(in+out) in [0,1] —
    high for drivers/entry points that call much but are called little. Never
    raises — returns neutral scores (0.0 / 0) on any failure.

    *derived_names* (declaration stubs / generated / build output) are excluded
    from the PageRank restart distribution rather than from the graph: mass
    still flows *into* them along real references, so a hand-written
    ``internal.d.ts`` type that the renderer genuinely leans on keeps its rank,
    but a wall of typedefs referencing each other no longer manufactures its
    own importance. Since ``_enrich`` prunes hub edges by target importance,
    this also makes a hub keep its real callees over its type annotations.
    """
    imp: Dict[str, float] = {n: 0.0 for n in names}
    comm: Dict[str, int] = {n: 0 for n in names}
    refcnt: Dict[str, int] = {n: 0 for n in names}
    entry: Dict[str, float] = {n: 0.0 for n in names}
    derived_names = derived_names or set()
    try:
        g = graph.get_graph()
        n2v = graph.name_to_vertex
        vids = [n2v[n] for n in names if n in n2v]
        if len(vids) < 3:
            return imp, comm, refcnt, entry
        sub = g.subgraph(vids)
        ref_eids = [
            e.index for e in sub.es if e.attributes().get("type") == "reference"
        ]
        subref = sub.subgraph_edges(ref_eids, delete_vertices=False)
        sub_names = list(subref.vs["name"])
        pr = _pagerank(subref, sub_names, derived_names)
        order = sorted(range(len(pr)), key=lambda i: pr[i])
        denom = max(1, len(pr) - 1)
        for rank, i in enumerate(order):
            imp[sub_names[i]] = round(rank / denom, 4)
        indeg = subref.indegree()
        outdeg = subref.outdegree()
        for i, nm in enumerate(sub_names):
            refcnt[nm] = int(indeg[i])
            tot = indeg[i] + outdeg[i]
            entry[nm] = round(outdeg[i] / tot, 4) if tot else 0.0
        membership = [0] * subref.vcount()
        if subref.vcount() >= 12:
            try:
                gu = subref.as_undirected(mode="collapse")
                cl = gu.community_leiden(
                    objective_function="modularity", n_iterations=-1
                )
                if cl.modularity is not None and cl.modularity >= 0.2:
                    membership = list(cl.membership)
            except Exception:  # noqa: BLE001 - community is optional polish
                pass
        for i, nm in enumerate(sub_names):
            comm[nm] = int(membership[i])
    except Exception:  # noqa: BLE001 - scoring is best-effort, never 500 the map
        pass
    return imp, comm, refcnt, entry


def _enrich(
    graph: CodeGraph,
    nodes: List[Dict[str, Any]],
    edges: List[Dict[str, Any]],
    derived: Optional[_DerivedFiles] = None,
    hub_cap: int = 8,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Tag nodes with importance/community and prune high-out-degree hubs.

    A node with more than *hub_cap* outgoing edges keeps only the edges to its
    highest-importance targets; the rest are folded away and counted in
    ``hidden_callees`` so the UI can badge "+N". Nodes left fully disconnected by
    that fold (the low-value leaf tail) are dropped unless they're a seed/root.
    This keeps dense, high-fan-out maps from becoming hairballs.

    Nodes from derived files are flagged ``declaration`` so the UI can dim them,
    and are held out of the PageRank restart set (see :func:`_score`).
    """
    derived = derived or _DerivedFiles()
    derived_names: Set[str] = set()
    for n in nodes:
        source_path = n.get("file")
        if not source_path and n.get("kind") == NODE_TYPE_FILE:
            source_path = n.get("name")
        n["declaration"] = derived(source_path)
        if n["declaration"]:
            derived_names.add(n["name"])
    imp, comm, refcnt, entry = _score(graph, [n["name"] for n in nodes], derived_names)
    for n in nodes:
        n["importance"] = imp.get(n["name"], 0.0)
        n["community"] = comm.get(n["name"], 0)
        n["ref_count"] = refcnt.get(n["name"], 0)
        n["entry_score"] = entry.get(n["name"], 0.0)
    # Edge weight = number of distinct SCIP/LSP-exact call sites. Callers that
    # retain only an anchor sample set the exact count before enrichment.
    for e in edges:
        e.setdefault("weight", len(e.get("anchors") or []))

    imp_by_id = {n["id"]: n.get("importance", 0.0) for n in nodes}
    by_src: Dict[str, List[Dict[str, Any]]] = {}
    for e in edges:
        by_src.setdefault(e["source"], []).append(e)
    kept: List[Dict[str, Any]] = []
    hidden: Dict[str, int] = {}
    for src, es in by_src.items():
        if len(es) <= hub_cap:
            kept.extend(es)
            continue
        es_sorted = sorted(
            es, key=lambda e: imp_by_id.get(e["target"], 0.0), reverse=True
        )
        kept.extend(es_sorted[:hub_cap])
        hidden[src] = len(es) - hub_cap
    for n in nodes:
        if n["id"] in hidden:
            n["hidden_callees"] = hidden[n["id"]]
    connected = {e["source"] for e in kept} | {e["target"] for e in kept}
    nodes = [n for n in nodes if n["id"] in connected or n.get("is_root")]
    return nodes, kept


def build_codemap(
    graph: CodeGraph,
    symbol: Optional[str] = None,
    direction: str = "both",
    depth: int = 2,
    max_nodes: int = 40,
    repo_dir: Optional[str] = None,
    repo_commit: Optional[str] = None,
    hierarchy_graph: Optional[HierarchicalCodeGraph] = None,
    *,
    source_reader: Optional[RepositorySourceReader] = None,
    source_selection: Optional[RepositorySourceSelection] = None,
) -> Dict[str, Any]:
    """Return a dependency subgraph + Mermaid rendering around *symbol*.

    Args:
        graph: the repo's loaded :class:`CodeGraph`.
        symbol: focus symbol (readable name); ``None`` picks a central default.
        direction: ``"both"`` (callers + callees), ``"callees"`` (what it calls),
            or ``"callers"`` (what calls it).
        depth: BFS hops over reference edges (clamped to 1..4).
        max_nodes: node cap (clamped to 2..120); BFS stops adding past it.
    """
    direction = direction if direction in _DIR_TO_MODE else "both"
    depth = max(1, min(int(depth), 4))
    max_nodes = max(2, min(int(max_nodes), 120))
    note = ""

    def selected_source_path(value: object) -> Optional[str]:
        if not isinstance(value, str) or not value:
            return None
        if source_reader is not None:
            return source_reader.captured_relative_path(value)
        if source_selection is None:
            return value
        relative = (
            safe_repo_relative_path(repo_dir, value)
            if repo_dir
            else value.replace("\\", "/")
        )
        if relative is None or not repository_path_is_visible(
            relative,
            selection=source_selection,
        ):
            return None
        return relative

    policy_bound = source_reader is not None or source_selection is not None

    def source_allowed(attrs: Dict[str, Any]) -> bool:
        value = attrs.get("file")
        return (
            not isinstance(value, str)
            or not value
            or selected_source_path(value) is not None
        )

    def selected_edge_metadata(meta: Any) -> Any:
        if not policy_bound or not isinstance(meta, dict):
            return meta
        anchor_file = meta.get("anchor_file")
        if not anchor_file:
            return meta
        relative = selected_source_path(anchor_file)
        if relative is None:
            return None
        selected = dict(meta)
        selected["anchor_file"] = relative
        return selected

    derived = _DerivedFiles(
        repo_dir,
        repo_commit,
        source_reader=source_reader,
    )
    # Resolve a historical tree once for this request. The tiny process cache
    # is only a cross-request optimization and may be evicted by concurrent
    # maps; per-node classification must not depend on it staying hot.
    repo_paths: object = _GIT_PATHS_UNSET
    if source_reader is None and repo_dir and valid_commit(repo_commit):
        repo_paths = git_tree_paths(os.path.realpath(repo_dir), str(repo_commit))
    # Entry-point discovery currently reads manifests from a checkout. Historical
    # graph requests must not borrow declarations from a different commit.
    entry_paths = (
        []
        if repo_commit or source_reader is not None
        else [entry.path for entry in discover_entry_points(repo_dir)]
    )
    root = _resolve(graph, symbol) if symbol else None
    if root is not None and not source_allowed(_attrs(graph, root)):
        root = None
    if symbol and root is None:
        note = f"Symbol {symbol!r} not found — showing the repo's entry point."
    if root is None:
        root = _default_seed(
            graph,
            derived,
            entry_paths,
            source_allowed=source_allowed if policy_bound else None,
        )
    if root is None:
        return {
            "available": False,
            "root": "",
            "root_label": "",
            "direction": direction,
            "nodes": [],
            "edges": [],
            "hierarchy": empty_hierarchy(),
            "mermaid": "",
            "note": "This repo has no symbol graph.",
        }

    searcher = RepoDependencySearcher(graph)
    mode = _DIR_TO_MODE[direction]

    seen: Set[str] = {root}
    depth_of: Dict[str, int] = {root: 0}
    raw_edges: List[Tuple[str, str]] = []
    edge_seen: Set[Tuple[str, str]] = set()
    # Count distinct reference sites per edge and retain a bounded deterministic
    # sample so the UI can jump to source without scaling the payload with a hot
    # edge's full call-site population.
    edge_anchors = _EdgeAnchorCollector()
    queue: deque[str] = deque([root])
    truncated = False

    while queue:
        cur = queue.popleft()
        d = depth_of[cur]
        if d >= depth:
            continue
        neighbors, n_edges = searcher.get_neighbors(
            cur, direction=mode, etype_filter={"reference"}, ignore_test_file=True
        )
        # In ``both`` mode the same graph edges are returned again when the BFS
        # reaches their other endpoint.  Consume the complete parallel-edge
        # batch from the first scan only; CodeGraph already makes those anchors
        # distinct at insertion time.
        new_edge_keys: Set[Tuple[str, str]] = set()
        admitted_neighbors: Set[str] = set()
        for src, tgt, _w, meta in n_edges:
            if src == tgt:
                continue  # drop self-loops (recursion) — visual noise
            if policy_bound and (
                not source_allowed(_attrs(graph, src))
                or not source_allowed(_attrs(graph, tgt))
            ):
                continue
            meta = selected_edge_metadata(meta)
            if meta is None:
                continue
            admitted_neighbors.update((src, tgt))
            key = (src, tgt)
            if key not in edge_seen:
                edge_seen.add(key)
                raw_edges.append(key)
                new_edge_keys.add(key)
            if key in new_edge_keys:
                edge_anchors.add(key, meta)
        for nb in neighbors:
            if nb in seen:
                continue
            if policy_bound and (
                nb not in admitted_neighbors or not source_allowed(_attrs(graph, nb))
            ):
                continue
            if len(seen) >= max_nodes:
                truncated = True
                continue
            seen.add(nb)
            depth_of[nb] = d + 1
            queue.append(nb)

    id_of: Dict[str, str] = {}
    nodes: List[Dict[str, Any]] = []
    for i, name in enumerate(sorted(seen, key=lambda n: (depth_of.get(n, 9), n))):
        a = _attrs(graph, name)
        label = _label(a, name)
        start = a.get("start_line")
        nid = f"n{i}"
        id_of[name] = nid
        nodes.append(
            {
                "id": nid,
                "name": name,
                "label": label,
                "short": _short(label),
                "file": (
                    selected_source_path(a.get("file"))
                    if policy_bound
                    else a.get("file")
                ),
                "line": (start + 1) if isinstance(start, int) else None,
                "end_line": (
                    (a.get("end_line") + 1)
                    if isinstance(a.get("end_line"), int)
                    else None
                ),
                "kind": a.get("type") or "symbol",
                "depth": depth_of.get(name, 0),
                "is_root": name == root,
                "external": _is_external(
                    a,
                    repo_dir,
                    repo_commit,
                    repo_paths=repo_paths,
                    source_reader=source_reader,
                ),
            }
        )

    edges: List[Dict[str, Any]] = []
    for s, t in raw_edges:
        if s not in id_of or t not in id_of:
            continue
        edge: Dict[str, Any] = {"source": id_of[s], "target": id_of[t]}
        edge.update(edge_anchors.fields((s, t)))
        edges.append(edge)

    nodes, edges = _enrich(graph, nodes, edges, derived)
    hierarchy = (
        hierarchy_for_view(hierarchy_graph, nodes)
        if hierarchy_graph is not None
        else hierarchy_from_view_nodes(nodes)
    )
    edges = attach_edge_routes(edges, hierarchy)
    return {
        "available": True,
        "root": root,
        "root_label": _label(_attrs(graph, root), root),
        "direction": direction,
        "depth": depth,
        "truncated": truncated,
        "nodes": nodes,
        "edges": edges,
        "hierarchy": hierarchy,
        "mermaid": _to_mermaid(nodes, edges, id_of[root]),
        "note": note,
    }


def _mm_escape(text: str) -> str:
    """Neutralize characters that break a Mermaid quoted node label."""
    return text.replace('"', "'").replace("\n", " ").replace("[", "(").replace("]", ")")


def _to_mermaid(
    nodes: List[Dict[str, Any]], edges: List[Dict[str, str]], root_id: str
) -> str:
    lines = ["graph LR"]
    for n in nodes:
        # The ["..."] are Mermaid node-label syntax, not Python repr quoting.
        lines.append(f'  {n["id"]}["{_mm_escape(n["short"])}"]')  # noqa: B907
    for e in edges:
        lines.append(f'  {e["source"]} --> {e["target"]}')
    # Force readable labels: white box + dark text (the Mermaid neutral theme
    # otherwise renders low-contrast grey-on-grey on a dense graph).
    lines.append("  classDef default fill:#ffffff,stroke:#c9ccd1,color:#1f2937;")
    lines.append("  classDef root fill:#2d7ff9,stroke:#1b5fd0,color:#ffffff;")
    lines.append(f"  class {root_id} root;")
    return "\n".join(lines)


def _resolve_citation(
    graph: CodeGraph,
    cit: Dict[str, Any],
    by_loc: Dict[Tuple[str, int], str],
    by_file: Dict[str, List[Tuple[int, str]]],
    repo_dir: Optional[str] = None,
) -> Optional[str]:
    """Map a wiki citation (file + 1-based line, or node_name) to a graph identity.

    Prefers an exact ``(file, 0-based start)`` hit, then the nearest symbol start
    in that file (small tolerance), then a readable-name match.
    """
    f = cit.get("file")
    if isinstance(f, str) and repo_dir and os.path.isabs(f):
        try:
            relative = os.path.relpath(f, repo_dir)
            if relative != ".." and not relative.startswith("../"):
                f = relative.replace("\\", "/")
        except ValueError:
            pass
    sl = cit.get("start_line")
    candidates = by_file.get(f, []) if isinstance(f, str) else []
    if candidates and (
        cit.get("type") == "file"
        or (cit.get("node_name") or "").replace("\\", "/") == f
    ):
        stem_terms = [
            term
            for term in re.split(
                r"[^a-z0-9]+",
                os.path.splitext(os.path.basename(f))[0].lower(),
            )
            if len(term) >= 3
        ]

        def representative_score(item: Tuple[int, str]) -> Tuple[int, int, int]:
            start, name = item
            attrs = _attrs(graph, name)
            label = _label(attrs, name).lower()
            symbol_label = label.partition(":")[2] or label
            matches = sum(term in symbol_label for term in stem_terms)
            kind_rank = {
                "class": 0,
                "function": 1,
                "interface": 2,
                "method": 3,
            }.get(attrs.get("type"), 4)
            return (-matches, kind_rank, start)

        return min(candidates, key=representative_score)[1]
    if f and isinstance(sl, int):
        s0 = sl - 1  # citations are 1-based (CodeLocation); the graph is 0-based
        if (f, s0) in by_loc:
            return by_loc[(f, s0)]
        best, best_d = None, 3
        for s, name in by_file.get(f, []):
            d = abs(s - s0)
            if d < best_d:
                best, best_d = name, d
        if best:
            return best
    nm = cit.get("node_name")
    return _resolve(graph, nm) if nm else None


def _citation_file(cit: Dict[str, Any], repo_dir: Optional[str]) -> str:
    f = cit.get("file")
    if not isinstance(f, str) or not f:
        return ""
    if repo_dir and os.path.isabs(f):
        try:
            relative = os.path.relpath(f, repo_dir)
            if relative != ".." and not relative.startswith("../"):
                return relative.replace("\\", "/")
        except ValueError:
            pass
    return f.replace("\\", "/")


def _unmapped_citations_note(
    citations: List[Dict[str, Any]],
    by_file: Dict[str, List[Tuple[int, str]]],
    repo_dir: Optional[str],
) -> str:
    """Say why none of a page's citations resolved, in terms a reader can act on.

    "Rebuild the graph" is only the right advice when the cited files *are* in
    the graph and the lines no longer line up. Pages about tests cite files the
    graph never indexes, and a C graph cannot map a page about Python tooling;
    telling the operator to rebuild would not change either.
    """

    from ..ops.filter import is_test_path

    count = len(citations)
    cited = f"{count} source location{'s' if count != 1 else ''}"
    files = {f for f in (_citation_file(cit, repo_dir) for cit in citations) if f}
    test_files = sorted(f for f in files if is_test_path(f))
    # A test file the graph did index still resolves poorly: its citations
    # span whole test bodies while the graph holds scattered fixtures, so a
    # miss there says nothing about the snapshot. Only a non-test file that is
    # in the graph and still fails to line up points at stale line numbers.
    stale = any(f in by_file and f not in test_files for f in files)
    if not by_file or not files or stale:
        return (
            f"This page cites {cited}, but none match symbols in the active "
            "graph snapshot. Rebuild the symbol graph from the same repository "
            "snapshot as the Wiki indexes."
        )
    if len(test_files) == len(files):
        return (
            f"This page cites {cited}, all in test files, which the symbol "
            "graph does not index."
        )
    graph_exts = sorted({os.path.splitext(f)[1] for f in by_file} - {""})
    cited_exts = sorted({os.path.splitext(f)[1] for f in files} - {""})
    if cited_exts and graph_exts and not set(cited_exts) & set(graph_exts):
        return (
            f"This page cites {cited} in {', '.join(cited_exts)} files, but the "
            f"symbol graph only indexes {', '.join(graph_exts)} files. Index "
            "those languages to map this page."
        )
    examples = ", ".join(sorted(f for f in files if f not in test_files)[:2])
    if test_files:
        return (
            f"This page cites {cited}; {len(test_files)} of its {len(files)} "
            "files are test files, which the symbol graph does not index, and "
            f"the rest (e.g. {examples}) were not indexed either."
        )
    return (
        f"This page cites {cited} in files the symbol graph did not index "
        f"(e.g. {examples})."
    )


def build_page_subgraph(
    graph: CodeGraph,
    citations: List[Dict[str, Any]],
    max_nodes: int = 18,
    repo_dir: Optional[str] = None,
    hierarchy_graph: Optional[HierarchicalCodeGraph] = None,
    *,
    source_reader: Optional[RepositorySourceReader] = None,
) -> Dict[str, Any]:
    """Page-evidence-first reference subgraph over a wiki page's cited symbols.

    Resolves each citation to a graph node, then returns the cited nodes plus
    direct reference edges between them. It admits only a tiny number of
    non-cited bridge symbols, and only when a bridge touches multiple cited
    symbols. That keeps the wiki map grounded in the page's evidence instead of
    dragging in a one-hop neighbourhood that may be true code but not relevant
    to the page.
    """
    max_nodes = max(2, min(int(max_nodes), 40))
    g = graph.get_graph()

    def selected_source_path(value: object) -> Optional[str]:
        if not isinstance(value, str) or not value:
            return None
        if source_reader is None:
            return value
        return source_reader.captured_relative_path(value)

    def source_allowed(name: str) -> bool:
        if source_reader is None:
            return True
        value = _attrs(graph, name).get("file")
        return (
            not isinstance(value, str)
            or not value
            or selected_source_path(value) is not None
        )

    def selected_edge_metadata(meta: Any) -> Any:
        if source_reader is None or not isinstance(meta, dict):
            return meta
        anchor_file = meta.get("anchor_file")
        if not anchor_file:
            return meta
        relative = selected_source_path(anchor_file)
        if relative is None:
            return None
        selected = dict(meta)
        selected["anchor_file"] = relative
        return selected

    # Location + name index for resolving citations precisely (built once).
    by_loc: Dict[Tuple[str, int], str] = {}
    by_file: Dict[str, List[Tuple[int, str]]] = {}
    for v in g.vs:
        a = v.attributes()
        f = a.get("file")
        s = a.get("start_line")
        if not f or not isinstance(s, int) or not a.get("unified_name"):
            continue
        normalized_file = selected_source_path(f)
        if normalized_file is None:
            continue
        if source_reader is None and repo_dir and os.path.isabs(f):
            try:
                relative = os.path.relpath(f, repo_dir)
                if relative != ".." and not relative.startswith("../"):
                    normalized_file = relative.replace("\\", "/")
            except ValueError:
                pass
        by_loc.setdefault((normalized_file, s), a["name"])
        by_file.setdefault(normalized_file, []).append((s, a["name"]))

    names: List[str] = []
    chosen: Set[str] = set()
    for cit in citations:
        if source_reader is not None:
            citation_file = selected_source_path(cit.get("file"))
            if citation_file is None:
                continue
            cit = dict(cit)
            cit["file"] = citation_file
        nm = _resolve_citation(graph, cit, by_loc, by_file, repo_dir)
        if nm and source_allowed(nm) and nm not in chosen:
            chosen.add(nm)
            names.append(nm)
        if len(names) >= max_nodes:
            break

    if not names:
        if citations:
            note = _unmapped_citations_note(citations, by_file, repo_dir)
        else:
            note = "This page has no source citations to map yet."
        return {
            "available": False,
            "root": "",
            "root_label": "",
            "direction": "both",
            "nodes": [],
            "edges": [],
            "hierarchy": empty_hierarchy(),
            "mermaid": "",
            "note": note,
        }

    seeds = set(names)  # the page's own cited symbols (highlighted)
    searcher = RepoDependencySearcher(graph)

    direct_edges: List[Tuple[str, str]] = []
    direct_seen: Set[Tuple[str, str]] = set()
    bridge_edges: Dict[str, Set[Tuple[str, str]]] = {}
    bridge_touches: Dict[str, Set[str]] = {}
    candidate_order: Dict[str, int] = {}
    edge_anchors = _EdgeAnchorCollector()
    anchor_edges_seen: Set[Tuple[str, str]] = set()

    def add_anchor(key: Tuple[str, str], meta: Any) -> None:
        edge_anchors.add(key, meta)

    for seed in names:
        _, n_edges = searcher.get_neighbors(
            seed, direction="all", etype_filter={"reference"}, ignore_test_file=True
        )
        new_anchor_keys: Set[Tuple[str, str]] = set()
        for src, tgt, _w, meta in n_edges:
            if src == tgt:
                continue
            if not source_allowed(src) or not source_allowed(tgt):
                continue
            meta = selected_edge_metadata(meta)
            if meta is None:
                continue
            key = (src, tgt)
            if key not in anchor_edges_seen:
                anchor_edges_seen.add(key)
                new_anchor_keys.add(key)
            if key in new_anchor_keys:
                add_anchor(key, meta)
            if src in seeds and tgt in seeds:
                if key not in direct_seen:
                    direct_seen.add(key)
                    direct_edges.append(key)
                continue

            other = tgt if src == seed else src if tgt == seed else None
            if other is None or other in seeds:
                continue
            other_attrs = _attrs(graph, other)
            if _is_external(
                other_attrs,
                repo_dir,
                source_reader=source_reader,
            ):
                continue
            candidate_order.setdefault(other, len(candidate_order))
            bridge_edges.setdefault(other, set()).add(key)
            bridge_touches.setdefault(other, set()).add(seed)

    bridge_weight = {
        name: sum(max(1, edge_anchors.count(key)) for key in keys)
        for name, keys in bridge_edges.items()
    }

    # A bridge has to explain relationships among page evidence, not merely be a
    # random one-hop neighbour of one citation. Rank by exact call-site evidence
    # first so broad generic types like Context do not crowd out stronger domain
    # connectors.
    bridge_candidates = [
        name for name, touches in bridge_touches.items() if len(touches) >= 2
    ]
    bridge_candidates.sort(
        key=lambda name: (
            -bridge_weight.get(name, 0),
            -len(bridge_touches.get(name, set())),
            candidate_order.get(name, 0),
            name,
        )
    )
    bridge_budget = min(2, max(0, max_nodes - len(names)))
    bridges = bridge_candidates[:bridge_budget]
    names = names[:max_nodes] + [b for b in bridges if b not in chosen]
    names = names[:max_nodes]
    nameset = set(names)

    edge_order: List[Tuple[str, str]] = []
    edge_seen: Set[Tuple[str, str]] = set()
    for key in direct_edges:
        if key[0] in nameset and key[1] in nameset and key not in edge_seen:
            edge_seen.add(key)
            edge_order.append(key)
    for bridge in bridges:
        for key in sorted(bridge_edges.get(bridge, set())):
            if key[0] in nameset and key[1] in nameset and key not in edge_seen:
                edge_seen.add(key)
                edge_order.append(key)

    # Collect anchors for any direct seed-seed edges that were not observed from
    # the first seed's neighbour walk due traversal direction/order.
    for nm in nameset:
        _, n_edges = searcher.get_neighbors(
            nm, direction="all", etype_filter={"reference"}, ignore_test_file=True
        )
        new_anchor_keys = set()
        for src, tgt, _w, meta in n_edges:
            if src == tgt or src not in nameset or tgt not in nameset:
                continue
            if not source_allowed(src) or not source_allowed(tgt):
                continue
            meta = selected_edge_metadata(meta)
            if meta is None:
                continue
            key = (src, tgt)
            touches_seed = src in seeds or tgt in seeds
            if not touches_seed:
                continue
            if key not in edge_seen and src in seeds and tgt in seeds:
                edge_seen.add(key)
                edge_order.append(key)
            if key not in anchor_edges_seen:
                anchor_edges_seen.add(key)
                new_anchor_keys.add(key)
            if key in edge_seen and key in new_anchor_keys:
                add_anchor(key, meta)

    # Order seeds first (they're the page's subject); neighbours follow.
    ordered = [n for n in names if n in seeds] + [n for n in names if n not in seeds]
    id_of: Dict[str, str] = {}
    nodes: List[Dict[str, Any]] = []
    for i, name in enumerate(ordered):
        a = _attrs(graph, name)
        label = _label(a, name)
        start = a.get("start_line")
        file = a.get("file")
        if source_reader is not None and isinstance(file, str):
            file = selected_source_path(file)
        elif repo_dir and isinstance(file, str) and os.path.isabs(file):
            try:
                relative = os.path.relpath(file, repo_dir)
                if relative != ".." and not relative.startswith("../"):
                    file = relative.replace("\\", "/")
            except ValueError:
                pass
        nid = f"n{i}"
        id_of[name] = nid
        nodes.append(
            {
                "id": nid,
                "name": name,
                "label": label,
                "short": _short(label),
                "file": file,
                "line": (start + 1) if isinstance(start, int) else None,
                "end_line": (
                    (a.get("end_line") + 1)
                    if isinstance(a.get("end_line"), int)
                    else None
                ),
                "kind": a.get("type") or "symbol",
                "depth": 0 if name in seeds else 1,
                "is_root": name in seeds,  # highlight the page's own symbols
                "external": _is_external(
                    a,
                    repo_dir,
                    source_reader=source_reader,
                ),
            }
        )

    edges: List[Dict[str, Any]] = []
    for s, t in edge_order:
        if s not in id_of or t not in id_of:
            continue
        edge: Dict[str, Any] = {"source": id_of[s], "target": id_of[t]}
        edge.update(edge_anchors.fields((s, t)))
        edges.append(edge)

    nodes, edges = _enrich(
        graph,
        nodes,
        edges,
        _DerivedFiles(repo_dir, source_reader=source_reader),
    )
    hierarchy = (
        hierarchy_for_view(hierarchy_graph, nodes)
        if hierarchy_graph is not None
        else hierarchy_from_view_nodes(nodes)
    )
    edges = attach_edge_routes(edges, hierarchy)
    return {
        "available": True,
        "root": "",
        "root_label": "",
        "direction": "both",
        "depth": 1,
        "truncated": len(names) >= max_nodes,
        "nodes": nodes,
        "edges": edges,
        "hierarchy": hierarchy,
        "mermaid": "",
        "note": "",
    }


def _page_seed_names(
    graph: CodeGraph,
    citations: List[Dict[str, Any]],
    max_nodes: int,
    repo_dir: Optional[str],
    source_reader: Optional[RepositorySourceReader] = None,
) -> List[str]:
    """Resolve a page's citations to graph identities, in citation order.

    Mirrors the seed resolution in ``build_page_subgraph``: with a bound
    source reader, citations and symbols outside the captured source are
    dropped rather than resolved against the live checkout.
    """

    g = graph.get_graph()

    def selected_source_path(value: object) -> Optional[str]:
        if not isinstance(value, str) or not value:
            return None
        if source_reader is None:
            return value
        return source_reader.captured_relative_path(value)

    def source_allowed(name: str) -> bool:
        if source_reader is None:
            return True
        value = _attrs(graph, name).get("file")
        return (
            not isinstance(value, str)
            or not value
            or selected_source_path(value) is not None
        )

    by_loc: Dict[Tuple[str, int], str] = {}
    by_file: Dict[str, List[Tuple[int, str]]] = {}
    for v in g.vs:
        a = v.attributes()
        f = a.get("file")
        s = a.get("start_line")
        if not f or not isinstance(s, int) or not a.get("unified_name"):
            continue
        normalized_file = selected_source_path(f)
        if normalized_file is None:
            continue
        if source_reader is None and repo_dir and os.path.isabs(f):
            try:
                relative = os.path.relpath(f, repo_dir)
                if relative != ".." and not relative.startswith("../"):
                    normalized_file = relative.replace("\\", "/")
            except ValueError:
                pass
        by_loc.setdefault((normalized_file, s), a["name"])
        by_file.setdefault(normalized_file, []).append((s, a["name"]))

    names: List[str] = []
    chosen: Set[str] = set()
    for cit in citations:
        if source_reader is not None:
            citation_file = selected_source_path(cit.get("file"))
            if citation_file is None:
                continue
            cit = dict(cit)
            cit["file"] = citation_file
        nm = _resolve_citation(graph, cit, by_loc, by_file, repo_dir)
        if nm and source_allowed(nm) and nm not in chosen:
            chosen.add(nm)
            names.append(nm)
        if len(names) >= max_nodes:
            break
    return names


# Rows per side of a page's boundary card, and how many one neighbouring file
# may claim before the rest are held back (the fact-card quota: without it a
# popular helper such as ``debugPrint`` fills the card).
_BOUNDARY_ROWS = 6
_BOUNDARY_PER_FILE = 2
# ...and how many rows one of the page's own symbols may take, so a popular
# helper the page happens to cite does not become the whole card.
_BOUNDARY_PER_PAGE_SYMBOL = 3
_CALLABLE_KINDS = {"function", "method"}


def _repo_file(
    file: Any,
    repo_dir: Optional[str],
    source_reader: Optional[RepositorySourceReader] = None,
) -> str:
    text = str(file or "")
    if source_reader is not None:
        return source_reader.captured_relative_path(text) or "" if text else ""
    if repo_dir and os.path.isabs(text):
        try:
            relative = os.path.relpath(text, repo_dir)
            if relative != ".." and not relative.startswith("../"):
                return relative.replace("\\", "/")
        except ValueError:
            pass
    return text


def build_page_boundary(
    graph: CodeGraph,
    citations: List[Dict[str, Any]],
    *,
    repo_dir: Optional[str] = None,
    max_rows: int = _BOUNDARY_ROWS,
    max_seeds: int = 18,
    source_reader: Optional[RepositorySourceReader] = None,
) -> Dict[str, Any]:
    """Who calls into a page's symbols, and what they call outside the page.

    The page's cited symbols are its subject. Every reference edge that crosses
    from outside that set in, or from inside it out, is a boundary handoff;
    each keeps its exact call sites. Tests are skipped, calls rank above field
    reads, and one far-side file may claim at most two rows, so the card shows
    the page's contract rather than one busy helper.
    """

    names = _page_seed_names(graph, citations, max_seeds, repo_dir, source_reader)
    empty = {
        "available": False,
        "focus": [],
        "inbound": [],
        "outbound": [],
        "truncated": False,
    }
    if not names:
        return empty
    seeds = set(names)
    searcher = RepoDependencySearcher(graph)
    anchors = _EdgeAnchorCollector()
    sides: Dict[str, Dict[Tuple[str, str], str]] = {"inbound": {}, "outbound": {}}
    seed_degree: Dict[str, int] = {}

    for seed in names:
        _, n_edges = searcher.get_neighbors(
            seed, direction="all", etype_filter={"reference"}, ignore_test_file=True
        )
        for src, tgt, _w, meta in n_edges:
            if src == tgt or (src in seeds and tgt in seeds):
                continue
            if src == seed:
                side, far = "outbound", tgt
            elif tgt == seed:
                side, far = "inbound", src
            else:
                continue
            far_attrs = _attrs(graph, far)
            if _is_external(far_attrs, repo_dir, source_reader=source_reader):
                continue
            far_file = _repo_file(far_attrs.get("file"), repo_dir, source_reader)
            if not far_file or is_test_file(far_file):
                continue
            key = (src, tgt)
            sides[side].setdefault(key, far_file)
            anchors.add(key, meta)
            seed_degree[seed] = seed_degree.get(seed, 0) + 1

    def row(key: Tuple[str, str], far_file: str, side: str) -> Dict[str, Any]:
        src, tgt = key
        far = src if side == "inbound" else tgt
        near = tgt if side == "inbound" else src
        far_attrs = _attrs(graph, far)
        start = far_attrs.get("start_line")
        fields = anchors.fields(key)
        return {
            "symbol": _label(far_attrs, far),
            "kind": far_attrs.get("type") or "symbol",
            "file": far_file,
            "line": start + 1 if isinstance(start, int) else None,
            "page_symbol": _label(_attrs(graph, near), near),
            "call": str(_attrs(graph, tgt).get("type") or "").lower()
            in _CALLABLE_KINDS,
            "count": max(1, anchors.count(key)),
            "anchors": [
                {
                    "file": _repo_file(item.get("file"), repo_dir, source_reader),
                    "line": item.get("line"),
                }
                for item in fields.get("anchors") or []
            ],
        }

    truncated = False
    result: Dict[str, List[Dict[str, Any]]] = {}
    for side, keyed in sides.items():
        rows = [row(key, far_file, side) for key, far_file in keyed.items()]
        rows.sort(
            key=lambda r: (not r["call"], -r["count"], r["symbol"], r["page_symbol"])
        )
        per_file: Dict[str, int] = {}
        per_near: Dict[str, int] = {}
        primary: List[Dict[str, Any]] = []
        overflow: List[Dict[str, Any]] = []
        for item in rows:
            seen = per_file.get(item["file"], 0)
            near = per_near.get(item["page_symbol"], 0)
            if (
                seen < _BOUNDARY_PER_FILE
                and near < _BOUNDARY_PER_PAGE_SYMBOL
                and len(primary) < max_rows
            ):
                per_file[item["file"]] = seen + 1
                per_near[item["page_symbol"]] = near + 1
                primary.append(item)
            else:
                overflow.append(item)
        kept = primary + overflow[: max(0, max_rows - len(primary))]
        truncated = truncated or len(rows) > len(kept)
        result[side] = kept

    touched = {r["page_symbol"] for rows in result.values() for r in rows}
    focus = []
    for name in names:
        attrs = _attrs(graph, name)
        label = _label(attrs, name)
        if label not in touched:
            continue
        start = attrs.get("start_line")
        focus.append(
            {
                "symbol": label,
                "file": _repo_file(attrs.get("file"), repo_dir, source_reader),
                "line": start + 1 if isinstance(start, int) else None,
                "degree": seed_degree.get(name, 0),
            }
        )
    return {
        "available": bool(result["inbound"] or result["outbound"]),
        "focus": focus,
        "inbound": result["inbound"],
        "outbound": result["outbound"],
        "truncated": truncated,
    }


def _mappable_symbol(graph: CodeGraph, name: str) -> bool:
    """A named code symbol, not a file node or a punctuation-only type."""

    attrs = _attrs(graph, name)
    if str(attrs.get("type") or "").lower() in {NODE_TYPE_FILE, "directory", "module"}:
        return False
    symbol = _label(attrs, name).split(":")[-1]
    return bool(re.search(r"[A-Za-z_]", symbol))


def build_area_map(
    graph: CodeGraph,
    areas: Sequence[Dict[str, Any]],
    *,
    repo_dir: Optional[str] = None,
    max_symbols_per_page: int = 18,
    source_reader: Optional[RepositorySourceReader] = None,
) -> Dict[str, Any]:
    """How a wiki's top-level areas call each other, read off the graph.

    ``areas`` are the outline's top-level pages, each with the citations of
    the area page and its children. A symbol belongs to the first area that
    cites it. Every reference edge whose two ends belong to different areas
    counts toward that area pair, and the pair keeps its strongest example
    call with its call site.
    """

    owner: Dict[str, str] = {}
    area_rows: List[Dict[str, Any]] = []
    for area in areas:
        area_id = str(area.get("id") or "")
        if not area_id:
            continue
        symbols: List[str] = []
        for citations in area.get("citations") or []:
            names = _page_seed_names(
                graph,
                list(citations or []),
                max_symbols_per_page,
                repo_dir,
                source_reader,
            )
            for name in names:
                if name not in owner and _mappable_symbol(graph, name):
                    owner[name] = area_id
                    symbols.append(name)
        files = {
            _repo_file(_attrs(graph, name).get("file"), repo_dir, source_reader)
            for name in symbols
        }
        area_rows.append(
            {
                "id": area_id,
                "title": str(area.get("title") or area_id),
                "symbols": len(symbols),
                "files": len({f for f in files if f}),
            }
        )

    searcher = RepoDependencySearcher(graph)
    links: Dict[Tuple[str, str], Dict[str, Any]] = {}
    pair_counts: Dict[Tuple[str, str], Dict[Tuple[str, str], int]] = {}
    pair_anchor: Dict[Tuple[str, str], Dict[str, Any]] = {}
    for name, area_id in owner.items():
        _, n_edges = searcher.get_neighbors(
            name, direction="out", etype_filter={"reference"}, ignore_test_file=True
        )
        for src, tgt, _w, meta in n_edges:
            if src != name or tgt not in owner:
                continue
            if tgt == src:
                continue
            other = owner[tgt]
            if other == area_id:
                continue
            key = (area_id, other)
            link = links.setdefault(
                key, {"source": area_id, "target": other, "weight": 0}
            )
            link["weight"] += 1
            calls = pair_counts.setdefault(key, {})
            calls[(src, tgt)] = calls.get((src, tgt), 0) + 1
            anchor_file = meta.get("anchor_file") if isinstance(meta, dict) else None
            anchor_line = meta.get("anchor_line") if isinstance(meta, dict) else None
            if anchor_file and (src, tgt) not in pair_anchor.setdefault(key, {}):
                pair_anchor[key][(src, tgt)] = {
                    "file": _repo_file(anchor_file, repo_dir, source_reader),
                    "line": anchor_line + 1 if isinstance(anchor_line, int) else None,
                }

    out_links: List[Dict[str, Any]] = []
    for key, link in links.items():
        calls = pair_counts[key]
        (src, tgt), _count = sorted(
            calls.items(),
            key=lambda item: (
                str(_attrs(graph, item[0][1]).get("type") or "").lower()
                not in _CALLABLE_KINDS,
                -item[1],
                item[0],
            ),
        )[0]
        out_links.append(
            {
                **link,
                "calls": len(calls),
                "example": {
                    "source": _label(_attrs(graph, src), src),
                    "target": _label(_attrs(graph, tgt), tgt),
                    "anchor": pair_anchor.get(key, {}).get((src, tgt)),
                },
            }
        )
    out_links.sort(key=lambda link: (-link["weight"], link["source"], link["target"]))
    return {
        "available": bool(area_rows) and bool(out_links),
        "areas": area_rows,
        "links": out_links,
    }
