# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Transactional catalog and immutable artifact storage contracts."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from codenib._lazy import exported_dir, load_export

if TYPE_CHECKING:  # pragma: no cover - imported only by static analyzers
    from .cas import BlobInfo, LocalCAS
    from .models import (
        DEFAULT_NAMESPACE_ID,
        DEFAULT_NAMESPACE_NAME,
        INDEX_JOB_REQUEST_CONTRACT,
        MAX_VIEW_GENERATION_MEMBERS,
        VIEW_GENERATION_MEMBERS_METADATA_KEY,
        ArtifactMember,
        IndexJobCompletion,
        IndexJobRecord,
        IndexJobRequest,
        IndexJobRequestedMode,
        IndexJobStatus,
        IndexJobViewRecord,
        NamespaceIdentity,
        ObjectRecord,
        PublishConflict,
        PublishedSnapshot,
        RefJobLease,
        RefState,
        RepositoryIdentity,
        SnapshotView,
        SourceRevision,
        StorageError,
        StorageIntegrityError,
        StorageNotFound,
        StorageValidationError,
        ViewGeneration,
        ViewProfile,
        canonical_utc_timestamp,
        normalize_view_generation_metadata,
        view_generation_member_digests,
    )
    from .protocols import (
        RETAINED_IMPORT_CATALOG_CONTRACT,
        RETAINED_IMPORT_RESPONSE_MAX_DEPTH,
        RETAINED_IMPORT_RESPONSE_MAX_KEY_CHARS,
        RETAINED_IMPORT_RESPONSE_MAX_NODES,
        RETAINED_IMPORT_RESPONSE_MAX_TEXT_CHARS,
        IndexCatalog,
        JobCatalog,
        ObjectStore,
        ReceiptRetainingObjectStore,
        ReceiptVerifyingObjectStore,
        RetainedImportCatalog,
        RetainedImportObjectStore,
        RetainedSnapshotCatalog,
        StreamingObjectStore,
    )
    from .sqlite_catalog import (
        CatalogConflictError,
        CatalogError,
        CatalogNotFoundError,
        CatalogValidationError,
        SQLiteCatalog,
    )
    from .view_bundle import (
        DEFAULT_MAX_BUNDLE_BYTES,
        DEFAULT_MAX_BUNDLE_FILES,
        DEFAULT_MAX_BUNDLE_METADATA_BYTES,
        VIEW_BUNDLE_MANIFEST,
        VIEW_BUNDLE_MEDIA_TYPE,
        VIEW_BUNDLE_PAYLOAD,
        VIEW_BUNDLE_SCHEMA,
        MaterializedViewBundle,
        PlannedViewBundle,
        ViewBundleRecord,
        build_view_bundle,
        consume_planned_view_bundle,
        consume_verified_view_bundle_stream,
        materialize_view_bundle,
        plan_view_bundle_reader,
        retry_retained_verified_bundle_stream_cleanup,
        validate_view_bundle_physical_size,
        verify_view_bundle,
    )


def _module_exports(module: str, *names: str) -> dict[str, tuple[str, str]]:
    qualified = f"{__name__}.{module}"
    return {name: (qualified, name) for name in names}


_EXPORTS = {
    **_module_exports(
        "cas",
        "BlobInfo",
        "LocalCAS",
    ),
    **_module_exports(
        "models",
        "DEFAULT_NAMESPACE_ID",
        "DEFAULT_NAMESPACE_NAME",
        "INDEX_JOB_REQUEST_CONTRACT",
        "MAX_VIEW_GENERATION_MEMBERS",
        "VIEW_GENERATION_MEMBERS_METADATA_KEY",
        "ArtifactMember",
        "IndexJobCompletion",
        "IndexJobRecord",
        "IndexJobRequest",
        "IndexJobRequestedMode",
        "IndexJobStatus",
        "IndexJobViewRecord",
        "NamespaceIdentity",
        "ObjectRecord",
        "PublishConflict",
        "PublishedSnapshot",
        "RefJobLease",
        "RefState",
        "RepositoryIdentity",
        "SnapshotView",
        "SourceRevision",
        "StorageError",
        "StorageIntegrityError",
        "StorageNotFound",
        "StorageValidationError",
        "ViewGeneration",
        "ViewProfile",
        "canonical_utc_timestamp",
        "normalize_view_generation_metadata",
        "view_generation_member_digests",
    ),
    **_module_exports(
        "protocols",
        "RETAINED_IMPORT_CATALOG_CONTRACT",
        "RETAINED_IMPORT_RESPONSE_MAX_DEPTH",
        "RETAINED_IMPORT_RESPONSE_MAX_KEY_CHARS",
        "RETAINED_IMPORT_RESPONSE_MAX_NODES",
        "RETAINED_IMPORT_RESPONSE_MAX_TEXT_CHARS",
        "IndexCatalog",
        "JobCatalog",
        "ObjectStore",
        "ReceiptRetainingObjectStore",
        "ReceiptVerifyingObjectStore",
        "RetainedImportCatalog",
        "RetainedImportObjectStore",
        "RetainedSnapshotCatalog",
        "StreamingObjectStore",
    ),
    **_module_exports(
        "sqlite_catalog",
        "CatalogConflictError",
        "CatalogError",
        "CatalogNotFoundError",
        "CatalogValidationError",
        "SQLiteCatalog",
    ),
    **_module_exports(
        "view_bundle",
        "DEFAULT_MAX_BUNDLE_BYTES",
        "DEFAULT_MAX_BUNDLE_FILES",
        "DEFAULT_MAX_BUNDLE_METADATA_BYTES",
        "VIEW_BUNDLE_MANIFEST",
        "VIEW_BUNDLE_MEDIA_TYPE",
        "VIEW_BUNDLE_PAYLOAD",
        "VIEW_BUNDLE_SCHEMA",
        "MaterializedViewBundle",
        "PlannedViewBundle",
        "ViewBundleRecord",
        "build_view_bundle",
        "consume_planned_view_bundle",
        "consume_verified_view_bundle_stream",
        "materialize_view_bundle",
        "plan_view_bundle_reader",
        "retry_retained_verified_bundle_stream_cleanup",
        "validate_view_bundle_physical_size",
        "verify_view_bundle",
    ),
}

__all__ = [
    "ArtifactMember",
    "BlobInfo",
    "CatalogConflictError",
    "CatalogError",
    "CatalogNotFoundError",
    "CatalogValidationError",
    "DEFAULT_MAX_BUNDLE_BYTES",
    "DEFAULT_MAX_BUNDLE_FILES",
    "DEFAULT_MAX_BUNDLE_METADATA_BYTES",
    "DEFAULT_NAMESPACE_ID",
    "DEFAULT_NAMESPACE_NAME",
    "INDEX_JOB_REQUEST_CONTRACT",
    "MAX_VIEW_GENERATION_MEMBERS",
    "IndexCatalog",
    "IndexJobCompletion",
    "IndexJobRecord",
    "IndexJobRequest",
    "IndexJobRequestedMode",
    "IndexJobStatus",
    "IndexJobViewRecord",
    "JobCatalog",
    "LocalCAS",
    "MaterializedViewBundle",
    "NamespaceIdentity",
    "ObjectRecord",
    "ObjectStore",
    "PlannedViewBundle",
    "PublishConflict",
    "PublishedSnapshot",
    "RefJobLease",
    "RefState",
    "ReceiptRetainingObjectStore",
    "ReceiptVerifyingObjectStore",
    "RETAINED_IMPORT_CATALOG_CONTRACT",
    "RETAINED_IMPORT_RESPONSE_MAX_DEPTH",
    "RETAINED_IMPORT_RESPONSE_MAX_KEY_CHARS",
    "RETAINED_IMPORT_RESPONSE_MAX_NODES",
    "RETAINED_IMPORT_RESPONSE_MAX_TEXT_CHARS",
    "RetainedImportCatalog",
    "RetainedImportObjectStore",
    "RetainedSnapshotCatalog",
    "RepositoryIdentity",
    "SQLiteCatalog",
    "SnapshotView",
    "SourceRevision",
    "StorageError",
    "StorageIntegrityError",
    "StorageNotFound",
    "StorageValidationError",
    "StreamingObjectStore",
    "VIEW_GENERATION_MEMBERS_METADATA_KEY",
    "VIEW_BUNDLE_MANIFEST",
    "VIEW_BUNDLE_MEDIA_TYPE",
    "VIEW_BUNDLE_PAYLOAD",
    "VIEW_BUNDLE_SCHEMA",
    "ViewBundleRecord",
    "ViewGeneration",
    "ViewProfile",
    "build_view_bundle",
    "canonical_utc_timestamp",
    "consume_planned_view_bundle",
    "consume_verified_view_bundle_stream",
    "materialize_view_bundle",
    "normalize_view_generation_metadata",
    "plan_view_bundle_reader",
    "retry_retained_verified_bundle_stream_cleanup",
    "view_generation_member_digests",
    "validate_view_bundle_physical_size",
    "verify_view_bundle",
]


def __getattr__(name: str) -> Any:
    return load_export(globals(), _EXPORTS, name)


def __dir__() -> list[str]:
    return exported_dir(globals(), _EXPORTS)
