# SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Transactional catalog and immutable artifact storage contracts."""

from .cas import BlobInfo, LocalCAS
from .models import (
    INDEX_JOB_REQUEST_CONTRACT,
    ArtifactMember,
    IndexJobCompletion,
    IndexJobRecord,
    IndexJobRequest,
    IndexJobRequestedMode,
    IndexJobStatus,
    IndexJobViewRecord,
    ObjectRecord,
    PublishConflict,
    PublishedSnapshot,
    RefJobLease,
    RefState,
    RepositoryIdentity,
    SnapshotView,
    SourceRevision,
    StorageError,
    StorageIntegrityError,
    StorageNotFound,
    StorageValidationError,
    ViewGeneration,
    ViewProfile,
)
from .protocols import (
    IndexCatalog,
    JobCatalog,
    ObjectStore,
    ReceiptVerifyingObjectStore,
)
from .sqlite_catalog import (
    DEFAULT_NAMESPACE_ID,
    CatalogConflictError,
    CatalogError,
    CatalogNotFoundError,
    CatalogValidationError,
    SQLiteCatalog,
)
from .view_bundle import (
    DEFAULT_MAX_BUNDLE_BYTES,
    DEFAULT_MAX_BUNDLE_FILES,
    DEFAULT_MAX_BUNDLE_METADATA_BYTES,
    VIEW_BUNDLE_MANIFEST,
    VIEW_BUNDLE_MEDIA_TYPE,
    VIEW_BUNDLE_PAYLOAD,
    VIEW_BUNDLE_SCHEMA,
    MaterializedViewBundle,
    ViewBundleRecord,
    build_view_bundle,
    materialize_view_bundle,
    validate_view_bundle_physical_size,
    verify_view_bundle,
)

__all__ = [
    "ArtifactMember",
    "BlobInfo",
    "CatalogConflictError",
    "CatalogError",
    "CatalogNotFoundError",
    "CatalogValidationError",
    "DEFAULT_MAX_BUNDLE_BYTES",
    "DEFAULT_MAX_BUNDLE_FILES",
    "DEFAULT_MAX_BUNDLE_METADATA_BYTES",
    "DEFAULT_NAMESPACE_ID",
    "INDEX_JOB_REQUEST_CONTRACT",
    "IndexCatalog",
    "IndexJobCompletion",
    "IndexJobRecord",
    "IndexJobRequest",
    "IndexJobRequestedMode",
    "IndexJobStatus",
    "IndexJobViewRecord",
    "JobCatalog",
    "LocalCAS",
    "MaterializedViewBundle",
    "ObjectRecord",
    "ObjectStore",
    "PublishConflict",
    "PublishedSnapshot",
    "RefJobLease",
    "RefState",
    "ReceiptVerifyingObjectStore",
    "RepositoryIdentity",
    "SQLiteCatalog",
    "SnapshotView",
    "SourceRevision",
    "StorageError",
    "StorageIntegrityError",
    "StorageNotFound",
    "StorageValidationError",
    "VIEW_BUNDLE_MANIFEST",
    "VIEW_BUNDLE_MEDIA_TYPE",
    "VIEW_BUNDLE_PAYLOAD",
    "VIEW_BUNDLE_SCHEMA",
    "ViewBundleRecord",
    "ViewGeneration",
    "ViewProfile",
    "build_view_bundle",
    "materialize_view_bundle",
    "validate_view_bundle_physical_size",
    "verify_view_bundle",
]
