// SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
// SPDX-License-Identifier: Apache-2.0
// Pre-render the pinned excerpts with the Wiki's existing syntax highlighter.
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import evidence from "../landing/assets/explore/requests.js";

const require = createRequire(new URL("../web/package.json", import.meta.url));
const hljs = require("highlight.js/lib/core");
hljs.registerLanguage("python", require("highlight.js/lib/languages/python"));
const fragments = Object.fromEntries(evidence.nodes.map(node => {
  const lines = node.content.trimEnd().split("\n");
  const indent = Math.min(...lines.filter(line => line.trim()).map(line => line.match(/^ */)[0].length));
  const code = lines.map(line => line.slice(indent)).join("\n");
  return [node.id, { sha256: node.sha256, html: hljs.highlight(code, { language: "python" }).value }];
}));
const output = `// SPDX-FileCopyrightText: 2025-2026 CodeNib Contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/highlight_first_visit_example.mjs; do not hand-edit.
export default ${JSON.stringify(fragments, null, 2)};
`;
const target = new URL("../landing/assets/explore/requests-highlight.js", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(target, "utf8") !== output) throw new Error("Homepage syntax differs from the pinned excerpts; regenerate it");
  console.log("Homepage syntax matches all four pinned excerpts");
} else {
  await writeFile(target, output);
  console.log("Highlighted all four homepage excerpts without runtime dependencies");
}
